path: D:\\  # dataset root dir
train: images\\train  # train images (relative to 'path')
val: images\\val  # val images (relative to 'path')
#test: test\\images  # test images (relative to 'path')

# Classes
names:
  0: license plate
